sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    # linux
    - os: linux
      env: NODE_VERSION="4"     # abi 46
    - os: linux
      env: NODE_VERSION="5"     # abi 47
    - os: linux
      env: NODE_VERSION="6"     # abi 48
    # os x x86
    - os: osx
      env: NODE_VERSION="4"
    - os: osx
      env: NODE_VERSION="5"
    - os: osx
      env: NODE_VERSION="6"
    # osx ia32
    - os: osx
      env: NODE_VERSION="4" TARGET_ARCH="ia32"
    - os: osx
      env: NODE_VERSION="5" TARGET_ARCH="ia32"
    - os: osx
      env: NODE_VERSION="6" TARGET_ARCH="ia32"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - if [[ $NODE_VERSION == "0.10" ]]; then
      npm -g install npm@latest-2;
    fi
  - export PATH="./node_modules/.bin/:$PATH"

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install

script:
  - if [[ -z "$TARGET_ARCH" ]]; then
      node-pre-gyp rebuild package testpackage --build-from-source;
      npm test;
    else
      node-pre-gyp rebuild package testpackage --build-from-source --target_arch=$TARGET_ARCH;
    fi

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/

before_deploy:
  - export RELEASE_NODE_FILE=$(find build/stage -name '*.tar.gz')
  - echo "Deploying $RELEASE_NODE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: rivjfcpvoU7OaTU7/UZIE2CWh54jxYi1WZ0Cl9EeKs18fHnnHKu/1V4Hb2FLeOd/ulVjDNxdtlc5YFJ1PpzIGTARtUckb4YDQGUOXPHLSZflCO0TTJP+38QIwTcGbEa+VbXjJqHIbzMnKKyWZNqx2tzevnvjXbzExZubkddk6EBIUQQglrXgUPFedUxk5cWr82iwNw4/trq9mURihVQpDFHmbbtcEieBHAjS+Yp4ZNkmd42Yljxppf54TAEadwflfJnhgs50P2Lc63Pj4dSDIKo6VytbH8odvXqVOJsCwFhcmHTshnrmrgO5FzNj/ECvZAmSWK65qUt0AuNCN8N9tK2LzMHdzcOA0hOqZuCIWXuI/AIF4AF/vjqs35qAgCmwOfmcxfBEX+hGtgU0qpYnrNLo2WpejrYsh0kJrr0tsQAqHJW90U/G0dGjeC3ZQTpX6D1kuq8yRYpelvIft+FzQaHaaPpOXq3LDzvQO9ZnHDpxBsLvWvfEjvq5P3pKUB52uBfh6y643fmVZxHSrYnxio9vCV/XR4zGwJLl6GCrz4pcBkwZT5K1wP/Fmgrs2/ueJiPKDaCYFe0oVFuwNhiZbv0PZfbg1lQz7bd931YZuUqgTNnaBEhStBEGdk1jkbNJYUOBSLPe/Querkw9ReeUDGr3+TnylmEZ9REDiMLV1LM=
  file: "$RELEASE_NODE_FILE"
  skip_cleanup: true
  on:
    repo: zertosh/ctags-prebuilt
    tags: true
