sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    # linux
    - os: linux   # abi 47
      env: NODE_VERSION="5.1.1" CXX="g++-4.8"
    - os: linux   # abi 48
      env: NODE_VERSION="6" CXX="g++-4.8"
    - os: linux   # abi 49
      env: NODE_VERSION="6" ELECTRON="1.3.6" CXX="g++-4.8"
    # os x x86
    - os: osx
      env: NODE_VERSION="5.1.1"
    - os: osx
      env: NODE_VERSION="6"
    - os: osx
      env: NODE_VERSION="6" ELECTRON="1.3.6"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - export PATH="./node_modules/.bin/:$PATH"

install:
  - if [[ -n "$ELECTRON" ]]; then
      export npm_config_target=$ELECTRON;
      export npm_config_disturl=https://atom.io/download/atom-shell;
      export npm_config_runtime=electron;
      export npm_config_build_from_source=true;
    fi
  - npm install

script:
  - if [[ -z "$ELECTRON" ]]; then
      npm test;
    fi
  - node-pre-gyp package testpackage

git:
  depth: 10

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/

before_deploy:
  - export RELEASE_NODE_FILE=$(find build/stage -name '*.tar.gz')
  - echo "Deploying $RELEASE_NODE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: rivjfcpvoU7OaTU7/UZIE2CWh54jxYi1WZ0Cl9EeKs18fHnnHKu/1V4Hb2FLeOd/ulVjDNxdtlc5YFJ1PpzIGTARtUckb4YDQGUOXPHLSZflCO0TTJP+38QIwTcGbEa+VbXjJqHIbzMnKKyWZNqx2tzevnvjXbzExZubkddk6EBIUQQglrXgUPFedUxk5cWr82iwNw4/trq9mURihVQpDFHmbbtcEieBHAjS+Yp4ZNkmd42Yljxppf54TAEadwflfJnhgs50P2Lc63Pj4dSDIKo6VytbH8odvXqVOJsCwFhcmHTshnrmrgO5FzNj/ECvZAmSWK65qUt0AuNCN8N9tK2LzMHdzcOA0hOqZuCIWXuI/AIF4AF/vjqs35qAgCmwOfmcxfBEX+hGtgU0qpYnrNLo2WpejrYsh0kJrr0tsQAqHJW90U/G0dGjeC3ZQTpX6D1kuq8yRYpelvIft+FzQaHaaPpOXq3LDzvQO9ZnHDpxBsLvWvfEjvq5P3pKUB52uBfh6y643fmVZxHSrYnxio9vCV/XR4zGwJLl6GCrz4pcBkwZT5K1wP/Fmgrs2/ueJiPKDaCYFe0oVFuwNhiZbv0PZfbg1lQz7bd931YZuUqgTNnaBEhStBEGdk1jkbNJYUOBSLPe/Querkw9ReeUDGr3+TnylmEZ9REDiMLV1LM=
  file: "$RELEASE_NODE_FILE"
  skip_cleanup: true
  on:
    repo: zertosh/ctags-prebuilt
    tags: true
